name: Run E2E

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js Version
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: npm ci --no-audit --fund false

      - name: Install & Start Ghost
        run: |
          mkdir app && cd $_
          npm i -g ghost-cli
          ghost install local --prompt false --auto --no-enable --start

      - name: Run Onboarding
        uses: cypress-io/github-action@v6.1.0
        with:
          browser: chrome
          env: excludedSpecPattern=cypress/e2e/onboarding.cy.js

      - name: Stop Ghost
        if: always()
        run: |
          cd app
          ghost stop
