name: Run Kraken E2E

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js Version
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: npm ci --no-audit --fund false

      - name: Install & Start Ghost
        run: |
          mkdir app && cd $_
          npm i -g ghost-cli
          ghost install local --prompt false --auto --no-enable --start

      - name: Run Onboarding
        uses: cypress-io/github-action@v6.1.0
        with:
          browser: chrome
          spec: e2e-cypress/cypress/e2e/onboarding.cy.js
          project: ./e2e-cypress

      - name: Run Kraken Tests
        run: npm run kraken:test

      - name: Stop Ghost
        if: always()
        run: |
          cd app
          ghost stop
