name: Run Kraken E2E

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js Version
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: npm ci --no-audit --fund false

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.1

      - name: Install & Start Ghost
        run: |
          mkdir app && cd $_
          npm i -g ghost-cli
          ghost install local --prompt false --auto --no-enable --start

      - name: Run Kraken Tests
        run: npm run kraken:test

      - name: Stop Ghost
        if: always()
        run: |
          cd app
          ghost stop
